"""add title and duration to videos

Revision ID: b236fba3d6d5
Revises: ac09b221c2a3
Create Date: 2026-07-08 03:48:30.065619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b236fba3d6d5'
down_revision: Union[str, Sequence[str], None] = 'ac09b221c2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('videos', sa.Column('duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'duration')
    op.drop_column('videos', 'title')
    # ### end Alembic commands ###
